apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-config
  labels:
    {{- include "petclinic.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.springProfiles | quote }}
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ .Values.eurekaUrl | quote }}
