{{- if .Values.hpa.enabled }}
{{- range $name, $svc := .Values.services }}
{{- if has $name $.Values.hpa.services }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}-hpa
  labels:
    app: {{ $name }}
    {{- include "petclinic.labels" $ | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $name }}
  minReplicas: {{ $.Values.hpa.minReplicas }}
  maxReplicas: {{ $.Values.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $.Values.hpa.cpuUtilization }}
{{- end }}
{{- end }}
{{- end }}
