apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: petclinic
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "petclinic-root"
  MYSQL_DATABASE: "petclinic"
  MYSQL_USER: "petclinic"
  MYSQL_PASSWORD: "petclinic"
